type Item = {
  collectable: boolean;
  duration: number;
  job: "BOT" | "MIN";
  level: number;
  name: string;
  stars: number;
  type: "item";
  xy: [number, number];
  zone: string;
};

type Empty = {
  type: "empty";
  duration: number;
};

export type Entry = Item | Empty;

export const earth: Entry[] = [
  {
    collectable: false,
    duration: 4,
    job: "MIN",
    level: 90,
    name: "Prime Siderite",
    stars: 2,
    type: "item",
    xy: [32, 35],
    zone: "Garlemald",
  },
  {
    collectable: false,
    duration: 4,
    job: "BOT",
    level: 60,
    name: "Humic Soil",
    stars: 0,
    type: "item",
    xy: [7, 28],
    zone: "The Dravanian Hinterlands",
  },
  {
    collectable: false,
    duration: 4,
    job: "MIN",
    level: 80,
    name: "Thunder Rock",
    stars: 2,
    type: "item",
    xy: [35, 31],
    zone: "Lakeland",
  },
  {
    collectable: false,
    duration: 4,
    job: "MIN",
    level: 90,
    name: "Prime Siderite",
    stars: 2,
    type: "item",
    xy: [32, 35],
    zone: "Garlemald",
  },
  {
    collectable: false,
    duration: 4,
    job: "MIN",
    level: 80,
    name: "Thunder Rock",
    stars: 2,
    type: "item",
    xy: [33, 19],
    zone: "Kholusia",
  },
  {
    collectable: false,
    duration: 4,
    job: "MIN",
    level: 100,
    name: "Electrocoal",
    stars: 0,
    type: "item",
    xy: [27, 12],
    zone: "Heritage Found",
  },
];

export const fire: Entry[] = [
  {
    collectable: false,
    duration: 4,
    job: "BOT",
    level: 90,
    name: "Prime Haritaki",
    stars: 3,
    type: "item",
    xy: [28, 26],
    zone: "Thavnair",
  },
  {
    collectable: false,
    duration: 4,
    job: "MIN",
    level: 60,
    name: "Radiant Fire Moraine",
    stars: 0,
    type: "item",
    xy: [26, 22],
    zone: "The Dravanian Forelands",
  },
  {
    collectable: false,
    duration: 4,
    job: "BOT",
    level: 90,
    name: "Sophora Roots",
    stars: 2,
    type: "item",
    xy: [11, 35],
    zone: "Labyrinthos",
  },
  {
    collectable: false,
    duration: 4,
    job: "BOT",
    level: 90,
    name: "Prime Haritaki",
    stars: 3,
    type: "item",
    xy: [28, 26],
    zone: "Thavnair",
  },
  {
    collectable: false,
    duration: 4,
    job: "BOT",
    level: 100,
    name: "Volcanic Grass",
    stars: 0,
    type: "item",
    xy: [27, 7],
    zone: "Living Memory",
  },
  {
    type: "empty",
    duration: 4,
  },
];

export const lightning: Entry[] = [
  {
    collectable: false,
    duration: 4,
    job: "MIN",
    level: 100,
    name: "Brightwind Ore",
    stars: 0,
    type: "item",
    xy: [10, 11],
    zone: "Living Memory",
  },
  {
    collectable: false,
    duration: 4,
    job: "BOT",
    level: 80,
    name: "Levin Mint",
    stars: 2,
    type: "item",
    xy: [22, 13],
    zone: "The Rak'tika Greatwood",
  },
  {
    collectable: false,
    duration: 2,
    job: "MIN",
    level: 90,
    name: "Prime Achondrite",
    stars: 3,
    type: "item",
    xy: [31, 23],
    zone: "Mare Lamentorum",
  },
  {
    collectable: false,
    duration: 2,
    job: "MIN",
    level: 76,
    name: "Solarite",
    stars: 0,
    type: "item",
    xy: [36, 31],
    zone: "Lakeland",
  },
  {
    collectable: false,
    duration: 4,
    job: "BOT",
    level: 80,
    name: "Levin Mint",
    stars: 2,
    type: "item",
    xy: [32, 37],
    zone: "Lakeland",
  },
  {
    collectable: false,
    duration: 4,
    job: "BOT",
    level: 70,
    name: "Yanxian Verbena",
    stars: 2,
    type: "item",
    xy: [32, 27],
    zone: "Yanxia",
  },
  {
    collectable: false,
    duration: 2,
    job: "MIN",
    level: 90,
    name: "Prime Achondrite",
    stars: 3,
    type: "item",
    xy: [31, 23],
    zone: "Mare Lamentorum",
  },
  {
    collectable: false,
    duration: 2,
    job: "MIN",
    level: 90,
    name: "Ghostly Umbral Rock",
    stars: 0,
    type: "item",
    xy: [10, 15],
    zone: "Mare Garlemald",
  },
];

export const water: Entry[] = [
  {
    collectable: false,
    duration: 2,
    job: "MIN",
    level: 90,
    name: "Prime Chloroschist",
    stars: 3,
    type: "item",
    xy: [11, 21],
    zone: "Labyrinthos",
  },
  {
    collectable: false,
    duration: 4,
    job: "BOT",
    level: 90,
    name: "Prime Sphongos",
    stars: 3,
    type: "item",
    xy: [9, 30],
    zone: "Elpis",
  },
  {
    collectable: false,
    duration: 2,
    job: "MIN",
    level: 60,
    name: "Radiant Astral Moraine",
    stars: 1,
    type: "item",
    xy: [26, 22],
    zone: "The Dravanian Forelands",
  },
  {
    collectable: false,
    duration: 2,
    job: "MIN",
    level: 60,
    name: "Radiant Astral Moraine",
    stars: 1,
    type: "item",
    xy: [29, 18],
    zone: "The Dravanian Hinterlands",
  },
  {
    collectable: false,
    duration: 4,
    job: "MIN",
    level: 90,
    name: "Prime Chloroschist",
    stars: 3,
    type: "item",
    xy: [11, 21],
    zone: "Labyrinthos",
  },
  {
    collectable: false,
    duration: 4,
    job: "BOT",
    level: 90,
    name: "Prime Sphongos",
    stars: 3,
    type: "item",
    xy: [9, 30],
    zone: "Elpis",
  },
  {
    collectable: false,
    duration: 2,
    job: "MIN",
    level: 60,
    name: "Radiant Astral Moraine",
    stars: 1,
    type: "item",
    xy: [25, 31],
    zone: "The Sea of Clouds",
  },
  {
    collectable: false,
    duration: 2,
    job: "MIN",
    level: 66,
    name: "Dacite",
    stars: 0,
    type: "item",
    xy: [29, 7],
    zone: "Yanxia",
  },
  {
    collectable: false,
    duration: 2,
    job: "MIN",
    level: 90,
    name: "Prime Chloroschist",
    stars: 3,
    type: "item",
    xy: [11, 21],
    zone: "Labyrinthos",
  },
];
